# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "maven" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"


  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: maven
    directory: /aggregator
    schedule:
      interval: daily

  - package-ecosystem: maven
    directory: /api
    schedule:
      interval: daily

  - package-ecosystem: maven
    directory: /assert/assert-core
    schedule:
      interval: daily

  - package-ecosystem: maven
    directory: /assert/assert-filter
    schedule:
      interval: daily

  - package-ecosystem: maven
    directory: /assert/assert-junit4
    schedule:
      interval: daily

  - package-ecosystem: maven
    directory: /assert/assert-junit5
    schedule:
      interval: daily

  - package-ecosystem: maven
    directory: /assert
    schedule:
      interval: daily

  - package-ecosystem: maven
    directory: /builder
    schedule:
      interval: daily

  - package-ecosystem: maven
    directory: /doc
    schedule:
      interval: daily

  - package-ecosystem: maven
    directory: /example/app-api
    schedule:
      interval: daily

  - package-ecosystem: maven
    directory: /example/app-assert
    schedule:
      interval: daily

  - package-ecosystem: maven
    directory: /example/app-core
    schedule:
      interval: daily

  - package-ecosystem: maven
    directory: /example/app-framework
    schedule:
      interval: daily

  - package-ecosystem: maven
    directory: /example/app-histogram
    schedule:
      interval: daily

  - package-ecosystem: maven
    directory: /example/app-itest
    schedule:
      interval: daily

  - package-ecosystem: maven
    directory: /example/app-model
    schedule:
      interval: daily

  - package-ecosystem: maven
    directory: /example/app-queue
    schedule:
      interval: daily

  - package-ecosystem: maven
    directory: /example/app-store
    schedule:
      interval: daily

  - package-ecosystem: maven
    directory: /example/app-ui
    schedule:
      interval: daily

  - package-ecosystem: maven
    directory: /example/app-web-ui
    schedule:
      interval: daily

  - package-ecosystem: maven
    directory: /example
    schedule:
      interval: daily

  - package-ecosystem: maven
    directory: /message/message-core
    schedule:
      interval: daily

  - package-ecosystem: maven
    directory: /message/message-http
    schedule:
      interval: daily

  - package-ecosystem: maven
    directory: /message/message-json
    schedule:
      interval: daily

  - package-ecosystem: maven
    directory: /message/message-sql
    schedule:
      interval: daily

  - package-ecosystem: maven
    directory: /message/message-text
    schedule:
      interval: daily

  - package-ecosystem: maven
    directory: /message/message-web
    schedule:
      interval: daily

  - package-ecosystem: maven
    directory: /message/message-xml
    schedule:
      interval: daily

  - package-ecosystem: maven
    directory: /message
    schedule:
      interval: daily

  - package-ecosystem: maven
    directory: /model
    schedule:
      interval: daily

  - package-ecosystem: maven
    directory: /report
    schedule:
      interval: daily

  - package-ecosystem: maven
    directory: /report/report-core
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /report/report-ng
    schedule:
      interval: daily

  - package-ecosystem: maven
    directory: /report/report-ng
    schedule:
      interval: daily

  - package-ecosystem: maven
    directory: /validation/coppice
    schedule:
      interval: daily

  - package-ecosystem: maven
    directory: /validation
    schedule:
      interval: daily

  - package-ecosystem: maven
    directory: /validation/validation-core
    schedule:
      interval: daily

  - package-ecosystem: maven
    directory: /validation/validation-junit4
    schedule:
      interval: daily

  - package-ecosystem: maven
    directory: /validation/validation-junit5
    schedule:
      interval: daily
