# .github/release.yml

changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: Breaking Changes
      labels:
        - breaking-change
    - title: Enhancements
      labels:
        - enhancement
    - title: Dependencies
      labels:
        - dependencies
    - title: Other Changes
      labels:
        - "*"