package com.mastercard.test.flow.assrt;

import com.mastercard.test.flow.Flow;

/**
 * The identity of one {@link Flow} execution, for attributing system logs to
 * it. Available to the test via {@link Assertion#correlation()} regardless of
 * whether log capture is configured, so test code need not change when
 * reporting is switched off.
 */
public interface Correlation {

	/**
	 * The primary identifier for this execution. Either extracted from the flow by
	 * the configured function, or generated by the runner: unique within the run
	 * and very unlikely to collide across concurrent runs.
	 *
	 * @return The identifier that the test should send to the system under test
	 */
	String id();

	/**
	 * Binds an additional identifier to this execution, e.g. a transaction ID that
	 * the system under test generated and returned in a response. Events carrying
	 * the alias are then attributed to this flow. An alias that is already bound to
	 * another execution in this run makes attribution ambiguous; such events are
	 * reported as unattributed rather than guessed.
	 *
	 * @param id The additional identifier
	 */
	void alias( String id );
}
